apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: node-container
          image: us.icr.io/benchsec-reg/basic-node:latest
          resources:
            limits:
              memory: '300Mi'
              cpu: '100m'
          ports:
            - containerPort: 80
        - name: daemon-container
          image: us.icr.io/benchsec-reg/trivy-summary:latest
          resources:
            limits:
              memory: '300Mi'
              cpu: '300m'
