import { ImageStats } from '../types'

export default {
  imageMap: {},
  byStarCount: [],
  byPullCount: [],
  byPublishDate: [],
  byAverageCve: [],
  byAverageFixable: [],
  byAverageUnfixable: [],
  cveStats: {},
  severityAverageAllImages: 0,
  unfixableSeverityAverageAllImages: 0,
  fixableSeverityAverageAllImages: 0,
  severityCounts: {
    criticalFixable: 0,
    criticalUnfixable: 0,
    highFixable: 0,
    highUnfixable: 0,
    mediumFixable: 0,
    mediumUnfixable: 0,
    lowFixable: 0,
    lowUnfixable: 0,
    unspecifiedFixable: 0,
    unspecifiedUnfixable: 0,
  },
  imagesBySeverity: {
    criticalFixable: [],
    criticalUnfixable: [],
    highFixable: [],
    highUnfixable: [],
    mediumFixable: [],
    mediumUnfixable: [],
    lowFixable: [],
    lowUnfixable: [],
    unspecifiedFixable: [],
    unspecifiedUnfixable: [],
  },
} as ImageStats
